#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Query that retrieves all configurations and their basic metadata.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>
PREFIX purl: <http://purl.org/dc/terms/>

SELECT ?model_config ?label ?desc ?input ?output ?cag ?timeInterval
WHERE {
  ?model_config a model:ModelConfiguration.
  ?model_config rdfs:label ?label.
  OPTIONAL{?model_config purl:description ?desc}.
  OPTIONAL{?model_config model:hasInput ?input}.
  OPTIONAL{?model_config model:hasOutput ?output}.
  OPTIONAL{?model_config model:hasCAG ?cag}.
  OPTIONAL{?model_config model:hasTimeInterval ?timeInterval}.
}