#+ method: GET
#+ summary: Given a model configuration URI, this query returns the inputs/outputs and their corresponding variable presentations, standard names and units.
#+ defaults:
#+   - config: https://w3id.org/mint/instance#pihm_cfg_simple2

PREFIX model: <https://w3id.org/mint/modelCatalog#>
SELECT  DISTINCT  ?prop ?io ?vp ?st ?units
WHERE {
  {
    ?_config_iri model:hasInput ?io.
  }UNION
  {
    ?_config_iri model:hasOutput ?io.
  }
  ?_config_iri ?prop ?io.
  ?io model:hasPresentation ?vp.
  OPTIONAL {?vp model:hasStandardVariable ?st.}
  OPTIONAL {?vp model:usesUnit ?units.}
}