#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET

#+ Query that retrieves all configurations and their basic metadata.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>
SELECT ?config ?label ?desc ?cat ?v
WHERE {
  ?config a model:ModelConfiguration.
  #TO DO
}