#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET

#+ summary: Query that returns a list of all available configurations, their inputs files and output files.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>
SELECT ?config
(GROUP_CONCAT(DISTINCT ?input;SEPARATOR=', ') AS ?input_variables)
(GROUP_CONCAT(DISTINCT ?output;SEPARATOR=', ') AS ?output_variables)
WHERE {
  ?config a model:ModelConfiguration.
  ?config model:hasInput ?input.
  ?config model:hasOutput ?output.
}
GROUP BY(?config)