#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Query that returns all existing configurations, the model and model version they belong to, their label and description associated to them.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mc: <https://w3id.org/mint/modelCatalog#>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT ?model_config ?label ?desc ?modelVersion ?model
WHERE {
  ?model_config a mc:ModelConfiguration.
  ?model_config rdfs:label ?label.
  OPTIONAL{?model_config dc:description ?desc}.
  ?model mc:hasVersion ?modelVersion.
  ?modelVersion mc:hasConfiguration ?model_config.
}