#+ method: GET
#+ summary: Given a model configuration URI, this query returns the inputs/outputs and their data types, corresponding variable presentations, standard names and units.
#+ defaults:
#+   - config: https://w3id.org/mint/instance/pihm

PREFIX model: <https://w3id.org/mint/modelCatalog#>

SELECT  DISTINCT  ?prop ?io ?format ?type ?vp ?st ?units
WHERE {
  {
    ?_config_iri model:hasInput ?io.
  }UNION
  {
    ?_config_iri model:hasOutput ?io.
  }
  ?_config_iri ?prop ?io.
   OPTIONAL {?io model:hasFormat ?format}
  ?io a ?type.
  FILTER(?type != model:DatasetSpecification).
  OPTIONAL {?io model:hasPresentation ?vp.?vp model:hasStandardVariable ?st.}
  OPTIONAL {?io model:hasPresentation ?vp.?vp model:usesUnit ?units.}
}
