#+ summary: Gets a list of all dataset entities.
#+ mime: application/ld+json
#+ tags:
#+   - ModelIngestion
#+ method: GET
#+ pagination: 50
#+ defaults:
#+   - graph: urn:x-arq:DefaultGraph

prefix sd: <https://w3id.org/okn/o/sd#>

CONSTRUCT {?s ?o ?p }
WHERE { 
  GRAPH <?_graph> {
    ?s a sd:DatasetSpecification .
    ?s ?o ?p
  }
}