#+ method: GET
#+ summary: Query that returns the explanation diagrams (and their metadata) associated with a model configuration
#+ defaults:
#+   - v: https://w3id.org/okn/i/mint/CYCLES

prefix sd: <https://w3id.org/okn/o/sd#>
prefix sdm: <https://w3id.org/okn/o/sdm#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix prov: <http://www.w3.org/ns/prov#>

SELECT distinct ?img ?label ?url ?desc ?source
from <http://ontosoft.isi.edu:3030/modelCatalog-1.0.0/data/mint> 
WHERE {
  ?_v_iri sdm:hasExplanationDiagram ?img .
  ?img rdfs:label ?label.
  ?img prov:value ?url.
  OPTIONAL{?img sd:description ?desc}
  OPTIONAL{?img prov:hadPrimarySource ?source}
}