#+ method: GET
#+ summary: This query returns the configurations compatible with input(s) of the given model configuration URI
#+ defaults:
#+   - config: https://w3id.org/mint/instance/pihm

PREFIX model: <https://w3id.org/mint/modelCatalog#>

SELECT DISTINCT ?comp_config
WHERE {
  ?_config_iri model:hasInput/model:hasPresentation/model:hasStandardVariable ?var.
  
  ?comp_config a model:ModelConfiguration.
  ?comp_config model:hasOutput/model:hasPresentation/model:hasStandardVariable ?var.
  
  FILTER(?comp_config != ?_config_iri)
}