#+ method: GET
#+ summary: Query that returns returns the variablePresentations associated to the provided input/output, and their units. Additionally, this query returns the variable presentation label, description, long name, short name and standard variable.
#+ defaults:
#+   - io: https://w3id.org/okn/i/mint/pihm_forc

prefix sdm: <https://w3id.org/okn/o/sdm#>
prefix sd: <https://w3id.org/okn/o/sd#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT distinct ?vp ?label ?shortName ?longName ?description ?unit ?sn ?rl
WHERE {
  ?_io_iri sd:hasPresentation ?vp.
  OPTIONAL{
    ?vp sd:usesUnit ?u.
    ?u rdfs:label ?unit.
  }.
  ?vp rdfs:label ?label.
  OPTIONAL{?vp sd:description ?description.}.
  OPTIONAL{?vp sd:hasLongName ?longName.}.
  OPTIONAL{?vp sd:hasShortName ?shortName.}.
  OPTIONAL{?vp sd:hasStandardVariable ?svn. ?svn rdfs:label ?sn}.
  OPTIONAL{?vp sd:hasRelevanceLevel ?rl.}.
}