#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Query that returns returns the variablePresentations associated to the provided input/output, and their units.
#+ defaults:
#+   - io: https://w3id.org/mint/instance#pihm_forc

PREFIX mc: <https://w3id.org/mint/modelCatalog#>
SELECT distinct ?vp ?unit
WHERE {
  ?_io_iri mc:hasPresentation ?vp.
  ?vp mc:usesUnit ?unit.
}