#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET

#+ summary: Query that returns a label, description, category and versions of each model

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mc: <https://w3id.org/mint/modelCatalog#>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT ?model ?label ?desc (GROUP_CONCAT(DISTINCT ?cat;SEPARATOR=', ') AS ?categories) (GROUP_CONCAT(DISTINCT ?v;SEPARATOR=', ') AS ?versions)
WHERE {
  ?model a mc:Model.
  ?model rdfs:label ?label.
  OPTIONAL{?model dc:description ?desc}.
  OPTIONAL{?model mc:hasModelCategory ?cat}.
  OPTIONAL{?model mc:hasVersion ?v}.
}group by ?model ?label ?desc
