#+ method: GET
#+ summary: Match a model by text in the uri
#+ defaults:
#+   - label: WGEN

prefix sdm: <https://w3id.org/okn/o/sdm#>

SELECT ?model 
WHERE {
  ?model a sdm:Model.
  FILTER REGEX(str(?model), ?_label_string) 
}
