#+ method: GET
#+ summary: Query that given a standard variable, returns the model configurations which produce output variables with that standard name.
#+ defaults:
#+   - std: land_surface__albedo

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mc: <https://w3id.org/mint/modelCatalog#>
PREFIX os: <http://ontosoft.org/software#>

SELECT DISTINCT ?model ?version ?configuration
WHERE {
  ?model a mc:Model.
  ?model os:hasSoftwareVersion ?version.
  ?version mc:hasConfiguration ?configuration.
  ?configuration mc:hasOutput ?output.
  ?output mc:hasPresentation ?vp.
  ?vp mc:hasStandardVariable ?_std_string.
}