#+ method: GET
#+ summary: Query that returns all existing configurations, the model and model version they belong to, their label and description associated to them.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sdm: <https://w3id.org/okn/o/sdm#>
prefix sd: <https://w3id.org/okn/o/sd#>

SELECT ?model_config ?label ?compLoc ?desc ?modelVersion ?model
WHERE {
  ?model_config a sdm:ModelConfiguration.
  ?model_config rdfs:label ?label.
  OPTIONAL{?model_config sd:hasComponentLocation ?compLoc}.
  OPTIONAL{?model_config sd:description ?desc}.
  ?model sd:hasVersion ?modelVersion.
  ?modelVersion sd:hasConfiguration ?model_config.
}