#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Query that given a standard variable, returns the models which produce output variables with a particular standard name (or canonical name)
#+ defaults:
#+   - std: land_surface__albedo

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>

SELECT DISTINCT ?model
WHERE {
  ?model a model:Model.
  ?model model:hasVersion ?version.
  ?version model:hasConfiguration ?config.
  ?config model:hasOutput ?output.
  ?output model:hasPresentation ?vp.
  ?vp model:hasStandardVariable ?_std_string.
}