#+ method: GET
#+ summary: Query that given a variable presentation, returns the models, versions and configurations which use or produce that variable. The query also retrieves whether the variable is used as an input or output.
#+ defaults:
#+   - var: https://w3id.org/mint/instance#DSSAT_SRAD

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mc: <https://w3id.org/mint/modelCatalog#>
PREFIX os: <http://ontosoft.org/software#>

SELECT DISTINCT ?model ?version ?isInput ?configuration
WHERE {
  ?model a mc:Model.
  ?model os:hasSoftwareVersion ?version.
  ?version mc:hasConfiguration ?configuration.
  ?configuration ?isInput ?io.
  ?io mc:hasPresentation ?_var_iri.
}