#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Query that returns the models associated to a particular category ?_cat
#+ defaults:
#+   - cat: Ecology

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>
SELECT ?model
WHERE {
  ?model a model:Model.
  ?model model:hasModelCategory ?_cat_string.
}