#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET

#+ Query that retrieves all models and their basic metadata.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>
SELECT ?model ?label ?desc ?cat ?v
WHERE {
  ?model a model:Model.
  ?model rdfs:label ?label.
  OPTIONAL{?model model:hasDescription ?desc}.
  OPTIONAL{?model model:hasCategory ?cat}.
  OPTIONAL{?model model:hasVersion ?v}.
}