#+ method: GET

#+ summary: Query that returns all available model categories

prefix sdm: <https://w3id.org/okn/o/sdm#>

SELECT distinct ?category
from <http://ontosoft.isi.edu:3030/modelCatalog-1.0.0/data/mint> 
WHERE {
  ?model a sdm:Model; 
         sdm:hasModelCategory ?category
}
