#+ method: GET
#+ summary: Query that returns the models associated to a particular category ?_cat
#+ defaults:
#+   - cat: Hydrology

prefix sdm: <https://w3id.org/okn/o/sdm#>
SELECT ?model
from <http://ontosoft.isi.edu:3030/modelCatalog-1.0.0/data/mint> 
WHERE {
  ?model a sdm:Model.
  ?model sdm:hasModelCategory ?_cat_string.
}