#+ method: GET
#+ summary: Query that returns returns all standard names that are associated to an output in the model catalog, along with their label, URI and description


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix mc: <https://w3id.org/mint/modelCatalog#>

select ?snlabel ?snURI (GROUP_CONCAT(DISTINCT ?desc;SEPARATOR='-- ') as ?descriptions) where {
   ?ds mc:hasOutput ?out.
   ?out mc:hasPresentation ?p.
  optional {?p <http://purl.org/dc/terms/description> ?desc}.
   ?p mc:hasStandardVariable ?snURI.
   ?snURI rdfs:label ?snlabel.
}group by ?snURI ?snlabel