#+ method: GET
#+ summary: Query that returns returns all standard names that are associated to an output in the model catalog, along with their label, URI and description


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sdm: <https://w3id.org/okn/o/sdm#>
prefix sd: <https://w3id.org/okn/o/sd#>

select ?snlabel ?snURI (GROUP_CONCAT(DISTINCT ?long;SEPARATOR='-- ') as ?longNames) (GROUP_CONCAT(DISTINCT ?desc;SEPARATOR='-- ') as ?descriptions) 
from <http://ontosoft.isi.edu:3030/modelCatalog-1.0.0/data/mint> 
where {
   ?ds sd:hasOutput ?out.
   ?out sd:hasPresentation ?p.
   optional {?p sd:hasLongName ?long}.
   optional {?p sd:description ?desc}.
   ?p sd:hasStandardVariable ?snURI.
   ?snURI rdfs:label ?snlabel.
}group by ?snURI ?snlabel