#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Given a CAG ?_cag, return all the processes and influences associated with it.
#+ defaults:
#+   - cag: https://w3id.org/mint/instance#cycles_cfg_simple_CAG

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>

SELECT ?process
(GROUP_CONCAT(DISTINCT ?influences;SEPARATOR=', ') AS ?process_influences)
WHERE {
  ?_cag_iri model:has_part ?process.
  ?process model:influences ?influences.
}
GROUP BY ?process