#+ method: GET
#+ summary: Given a CAG ?_cag, this query returns all the processes associated with it (and their dependencies).
#+ defaults:
#+   - cag: https://w3id.org/mint/instance#cycles_cfg_simple_CAG

PREFIX mc: <https://w3id.org/mint/modelCatalog#>

SELECT ?process
(GROUP_CONCAT(DISTINCT ?influences;SEPARATOR=', ') AS ?process_influences)
WHERE {
  ?_cag_iri mc:hasPart ?process.
  ?process mc:influences ?influences.
}
GROUP BY ?process