#+ method: GET
#+ summary: Query that given a standard variable name, returns its context metadata.
#+ defaults:
#+   - std: land_surface__albedo

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sd: <https://w3id.org/okn/o/sd#>

SELECT DISTINCT ?p ?o
WHERE {
  ?vp sd:hasStandardVariable ?sv.
  ?sv rdfs:label ?_std_string.
  ?sv ?p ?o 
}