#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ summary: Query that returns the variablePresentations associated to the provided input/output ?_io, and their units.
#+ defaults:
#+   - io: https://w3id.org/mint/instance#topo_rain

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX commons: <https://w3id.org/mint/commons#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>
SELECT ?vp ?unit
WHERE {
  ?_io_iri commons:hasPresentation ?vp.
  ?vp commons:usesUnit ?unit.
}