#+ endpoint: http://ontosoft.isi.edu:3030/ds/query
#+ method: GET
#+ defaults:
#+   - type: https://w3id.org/mint/instance#TOPOFLOW
#+ summary: Query that returns a list of the available configurations, input variables and output variables given a certain model iri ?_model

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX model: <https://w3id.org/mint/modelCatalog#>

SELECT ?config ?input ?output
WHERE {
  ?_model_iri a model:Model.
  ?_model_iri model:hasConfiguration ?config.
  ?config model:hasInput ?input.
  ?config model:hasOutput ?output.
}