#+ method: GET
#+ summary: Query that returns a text-based search on any label or description that matcher the input text. The text search is not case sensitive and not exact. The results return the matched description and the URI of the target entity

#+ defaults:
#+   - text: clay
#+   - graph: https://w3id.org/mint/instance/brandon_test_graph 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
prefix mc: <https://w3id.org/mint/modelCatalog#>

select ?w ?desc 
from ?_graph_iri
where {
  VALUES ?property { dc:description rdfs:label }
  ?w ?property ?desc.
  {
   ?w a mc:VariablePresentation.
  }
   union
  {
    ?w a <http://www.geoscienceontology.org/svo/svu#Variable>.
  }
  filter regex(str(?desc),?_text,"i")  
}