#+ method: GET
#+ summary: Query that returns models based on a text-based search on any label or description that matches the input text. 

#+ defaults:
#+   - text: cycles

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sdm: <https://w3id.org/okn/o/sdm#>
prefix sd: <https://w3id.org/okn/o/sd#>

select ?w ?desc 
from <http://ontosoft.isi.edu:3030/modelCatalog-1.0.0/data/mint> 
where {
  VALUES ?property { sd:description rdfs:label }
  ?w ?property ?desc.
  ?w a sdm:Model
  filter regex(str(?desc),?_text,"i")  
}