#+ method: GET
#+ summary: Query that returns models based on a text-based search on any label or description that matches the input text. 

#+ defaults:
#+   - text: cycles

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
prefix mc: <https://w3id.org/mint/modelCatalog#>

select ?w ?desc where {
  VALUES ?property { dc:description rdfs:label }
  ?w ?property ?desc.
  ?w a mc:Model
  filter regex(str(?desc),?_text,"i")  
}